Belt_Exam/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^main', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^travels/', include('apps.travels.urls', namespace='travels')),
    url(r'^beltexam/', include('apps.beltexam.urls', namespace='beltexam')),
]

apps/beltexam/urls.py
from django.conf.urls import url, include
from . import views
#from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
]

apps/travels/urls.py
from django.conf.urls import url, include
from . import views
#from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^destination/(?P<id>\d+)$', views.destination, name = 'destination'),
    url(r'^add$', views.add, name = 'add'),
    url(r'^create$', views.create, name = 'create'),
    url(r'^join$', views.join, name = 'join'),
]

apps/beltexam/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/travels/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_reg.models import Users

# Create your models here.
class UserManager(models.Manager):
    def add_user_to_trip(self, name, description, travel_start, travel_end, logged_id):
        errors = []
        if len(name) == 0:
            errors.append("Name is required")
        elif len(description) == 0:
            errors.append("Description  is required")
        elif Locations.usermanager.filter(name=name):
            errors.append("This Trip is already planned")
        if len(errors) is not 0:
            return (False, errors)
        else:
            t = Locations(name=name, description=description, travel_start=travel_start, travel_end=travel_end)
            t.save()
            print t.id
            trip = Locations.usermanager.get(id=t.id)
            user = Users.usermanager.get(id=logged_id)
            trip.travel_id.add(user)
            trip.planner_id = user
            trip.save()
            return (True, t)

    def join_user_to_trip(self, logged_id, place_id):
        t = Locations.usermanager.get(id=place_id)
        u = Users.usermanager.get(id=logged_id)
        t.travel_id.add(u)
        return (True, t)


class Locations(models.Model):
    travel_id = models.ManyToManyField(Users, related_name='usertotrip')
    planner_id = models.ForeignKey(Users, related_name='usertoplanner', null=True)
    name = models.CharField(max_length=45)
    description = models.CharField(max_length=45)
    travel_start = models.DateField(blank=True, null=True)
    travel_end = models.DateField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    usermanager = UserManager()

apps/beltexam/views.py
from django.shortcuts import render, redirect, HttpResponse
from . import models
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):

    return render (request, 'login_reg/index.html')

apps/travels/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Locations
from . import models
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    schedules = Locations.usermanager.filter(travel_id=request.session['logged_id'])
    others = Locations.usermanager.exclude(planner_id=request.session['logged_id']).exclude(travel_id=request.session['logged_id'])
    context={
        'schedules':schedules,
        'others':others,
    }
    return render(request, 'travels/index.html', context)

def destination(request, id):
    request.session['logged_id']
    destination = Locations.usermanager.get(id=id)
    planner = Locations.usermanager.filter(planner_id=id)
    print planner
    other_users = Locations.usermanager.filter(travel_id=id)
    context = {
        'name':destination.name,
        'first_name':destination.planner_id.first_name,
        'last_name':destination.planner_id.last_name,
        'description':destination.description,
        'start':destination.travel_start,
        'end':destination.travel_end,
        'other_users':other_users
    }
    return render(request, 'travels/destination.html', context)

def add(request):
    if request.method == 'POST':
        request.session['logged_id'] = request.POST['logged_id']
        try:
            request.session.pop('errors')
        except:
            pass
    return render(request, 'travels/add.html')

def create(request):
    if request.method == 'POST':
        request.session['logged_id']=request.POST['logged_id']
        result = Locations.usermanager.add_user_to_trip(request.POST['name'], request.POST['description'], request.POST['travel_start'], request.POST['travel_end'], request.POST['logged_id'])
        if result[0]:
            try:
                request.session.pop('errors')
            except:
                pass
            return redirect(reverse('travels:index'))
        else:
            request.session['errors'] = result[1]
        return redirect(reverse('travels:add'))
    else:
        return redirect(reverse('travels:add'))

def join(request):
    if request.method == 'POST':
        request.session['logged_id']=request.POST['logged_id']
        print request.session['logged_id']
        result =  Locations.usermanager.join_user_to_trip(request.POST['logged_id'], request.POST['place_id'])
        return redirect(reverse('travels:index'))

apps/beltexam/templates/travels/add.html
<!doctype html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>jQuery UI Datepicker - Default functionality</title>
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
      $( function() {
        $( "#datepicker,#datepickerII" ).datepicker({ dateFormat: 'yy-mm-dd' });
      } );
      </script>
    </head>
    <body>
        <a href="{% url 'travels:index' %}">Home</a>
        <a href="{% url 'login_reg:index' %}">Log Out</a>
        <h1>Add a Trip</h1>
        {% for error in request.session.errors %}
          <p>{{error}}</p>
        {% endfor %}
        <form class="" action="{% url 'travels:create' %}" method="post">
            {% csrf_token %}
            <h3>Destination:</h3>
            <input type="text" name="name" value="">
            <h3>Description:</h3>
            <input type="text" name="description" value="">
            <h3>Travel Date From:</h3>
            <input type="text" name="travel_start" id="datepicker">
            <h3>Travel Date To:</h3>
            <input type="text" name="travel_end" id="datepickerII">
            <input type="submit" name="" value="Add">
            <input type="hidden" name="logged_id" value="{{request.session.logged_id}}">
        </form>
    </body>
</html>

apps/beltexam/templates/travels/destination.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Destination Profile</title>
    </head>
    <body>
        <a href="{% url 'travels:index' %}">Home</a>
        <a href="{% url 'login_reg:index' %}">Log Out</a>
        <h1>{{name}}</h1>
        <p>Planned By: {{first_name}} {{last_name}}</p>
        <p>Description: {{description}}</p>
        <p>Travel Date From: {{start}}</p>
        <p>Travel Date To: {{end}}</p>
        <h1>Other users joining the trip</h1>
        {% for other_user in other_users %}
        <p>{{other_users.travel_id.first_name}} {{other_users.travel_id.first_name}}</p>
        {% endfor %}
    </body>
</html>

apps/beltexam/templates/travels/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Travels Home Page</title>
    </head>
    <body>
        <a href="{% url 'login_reg:index' %}">Log Out</a>
        <h1>Hello, {{request.session.first_name}}!</h1>
        <h4>Your Trip Schedule</h4>
        <table>
            <tr>
                <th>Destination |</th>
                <th>Travel Start Date |</th>
                <th>Travel End Date |</th>
                <th>Description |</th>
                <th>Trip Planner |</th>
            </tr>
            {% for schedule in schedules %}
            <tr>
                <td><a href="{% url 'travels:destination' id=schedule.id %}">{{schedule.name}}</a></td>
                <td>{{schedule.travel_start}}</td>
                <td>{{schedule.travel_end}}</td>
                <td>{{schedule.description}}</td>
                <td>{{schedule.planner_id.first_name}} {{schedule.planner_id.last_name}}</td>
            </tr>
            {% endfor %}
        </table>
        <h4>Other User's Travel Plans</h4>
        <table>
            <tr>
                <th>Name |</th>
                <th>Destination |</th>
                <th>Travel Start Date |</th>
                <th>Travel End Date |</th>
                <th>Do You Want to Join? |</th>
            </tr>
            {% for other in others %}
            <tr>
                <td>{{other.planner_id.first_name}} {{other.planner_id.last_name}}</td>
                <td><a href="{% url 'travels:destination' id=other.id %}">{{other.name}}</a></td>
                <td>{{other.travel_start}}</td>
                <td>{{other.travel_end}}</td>
                <td><form class="" action="{% url 'travels:join' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="place_id" value="{{other.id}}">
                    <input type="hidden" name="logged_id" value="{{request.session.logged_id}}">
                    <input type="submit" name="" value="Join!">
                </form></td>
            </tr>
            {% endfor %}
        </table>
        <form class="" action="{% url 'travels:add' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Add Travel Plan">
            <input type="hidden" name="logged_id" value="{{request.session.logged_id}}">
        </form>
    </body>
</html>