Belt_Exam/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^main', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^travels/', include('apps.travels.urls', namespace='travels')),
    url(r'^beltexam/', include('apps.beltexam.urls', namespace='beltexam')),
]

apps/beltexam/urls.py
from django.conf.urls import url, include
from . import views
#from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
]

apps/login_reg/urls.py
from django.conf.urls import url, include
from . import views
#from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^create$', views.create, name = 'create'),
    url(r'^success$', views.success)
]

apps/beltexam/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/login_reg/models.py
from __future__ import unicode_literals
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
import re, bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
USER_REGEX = re.compile(r'^[\w.-]+$')

class UserManager(models.Manager):
    def loginValid(self, email, password):
        errors =[]
        try:
            user = Users.usermanager.get(email=email)
            password = password.encode()
            hashed_pw = user.pw_hash.encode()
            print user
            print password
            print hashed_pw

            if hashed_pw == bcrypt.hashpw(password, hashed_pw):
                return(True, user)

        except ObjectDoesNotExist:
            errors.append("Incorrect Email/Password")
        return (False, errors)

    def registerValid(self, first_name, last_name, email, password, pass_conf):
        errors = []
        if len(email) == 0:
            errors.append("Email is required")
        elif not EMAIL_REGEX.match(email):
            errors.append("Invalid Email")
        elif len(first_name) < 2:
            errors.append("First name is required")
        elif not USER_REGEX.match(first_name):
            errors.append("Invalid first name")
        elif len(last_name) < 2:
            errors.append("Last name is required")
        elif not USER_REGEX.match(last_name):
            errors.append("Invalid last name")
        elif len(password) < 8:
            errors.append("Password is required")
        elif password != pass_conf:
            errors.append("Passwords do not match")
        elif Users.usermanager.filter(email=email):
            errors.append("Email already being used")
        if len(errors) is not 0:
            return (False, errors)
        else:
            pw_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            e = Users.usermanager.create(email=email, first_name=first_name, last_name=last_name, pw_hash=pw_hash)
            e.save()
            return (True, e)

# Create your models here.
class Users(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=100, null=False)
    pw_hash = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    usermanager = UserManager()

apps/beltexam/views.py
from django.shortcuts import render, redirect, HttpResponse
from . import models
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):

    return render (request, 'login_reg/index.html')

apps/login_reg/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Users
from . import models
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    if request.method == "POST":
        try:
            request.session.pop['logged_id']
        except:
            pass
    if not 'errors' in request.session:
        request.session['errors'] = []
    return render (request, 'login_reg/index.html')

def login(request):
    if request.method == "POST":
        result = Users.usermanager.loginValid(request.POST['email'],request.POST['password'])
        if result[0]:
            request.session['first_name'] = result[1].first_name
            request.session['logged_id'] = result[1].id
            try:
                request.session.pop('errors')
            except KeyError:
                pass
            return redirect(reverse('travels:index'))
        else:
            request.session['errors'] = result[1]
            return redirect(reverse('login_reg:index'))
    else:
        return redirect(reverse('login_reg:index'))

def create(request):
    if request.method == "POST":
        result = Users.usermanager.registerValid(request.POST['first_name'], request.POST['last_name'],request.POST['email'], request.POST['password'], request.POST['conf_pw'])
        if result[0]:
            request.session['first_name'] = result[1].first_name
            request.session['logged_id'] = result[1].id
            try:
                request.session.pop('errors')
            except:
                pass
            return redirect(reverse('travels:index'))
        else:
            request.session['errors'] = result[1]
            return redirect(reverse('login_reg:index'))
    else:
        return redirect(reverse('login_reg:index'))

def success(request):

    return render (request, 'login_reg/success.html', {'first_name': request.session.get('first_name')})

apps/beltexam/templates/login_reg/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Registration</title>
    </head>
    <body>
        {% for error in request.session.errors %}
          <p>{{error}}</p>
        {% endfor %}
        <h2>Login</h2>
        <form class="" action="{% url 'login_reg:login' %}" method="post">
            {% csrf_token %}
            <p>Email:</p>
            <input type="text" name="email" value="">
            <p>Password:</p>
            <input type="password" name="password" value="">
            <input type="submit" name="" value="Login">
        </form>
        <h2>Registration</h2>
        <form class="" action="{% url 'login_reg:create' %}" method="post">
            {% csrf_token %}
            <p>First Name:</p>
            <input type="text" name="first_name" value="">
            <p>Last Name:</p>
            <input type="text" name="last_name" value="">
            <p>Email:</p>
            <input type="text" name="email" value="">
            <p>Password:</p>
            <input type="password" name="password" value="">
            <p>Confirm Password:</p>
            <input type="password" name="conf_pw" value="">
            <input type="submit" name="" value="Register">
        </form>
    </body>
</html>

apps/beltexam/templates/login_reg/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Success!</title>
    </head>
    <body>
        <h1>Success! Welcome, {{first_name}}</h1>
    </body>
</html>